# Generated by Django 5.0.6 on 2024-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.ManyToManyField(to='courses.speciality')),
                ('teachers', models.ManyToManyField(to='courses.teacher')),
            ],
        ),
    ]
