# Generated by Django 5.0.6 on 2024-05-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_specialty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialty',
            new_name='Subject',
        ),
    ]
